### ISSUE TITLE
Release code date inquiry

### ISSUE THREAD

**Issue by sooftware** [Haoxiang-Wang/directional-preference-alignment#1]
Hi @Haoxiang-Wang !

I just wanted to drop a quick note to say thanks for all the amazing work on DPA! It's been incredibly helpful for my projects.

Also, could you share any info on when the code release might be? Just trying to plan ahead.

Thanks again for everything!

**Comment by Haoxiang-Wang** [comment]
Hi @sooftware , sorry, I am too busy these two weeks, so I don't have time for code cleaning & testing yet. Plan to release it by the end of this month.

**Comment by sooftware** [comment]
@Haoxiang-Wang Thanks for your quick response!
